### ISSUE TITLE
Duplicator crash when switching to Full Screen mode in external application

### ISSUE THREAD

**Issue by levantail** [smourier/Duplicator#3]
Duplicator works fine until switching to another application which displayed using Full Screen mode (e.g. game).

Log:
```
SharpDX.SharpDXException
  HResult=0x887A0026
  Message=HRESULT: [0x887A0026], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_ACCESS_LOST/AccessLost], Message: The keyed mutex was abandoned.

  Source=SharpDX
  StackTrace:
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.OutputDuplication.AcquireNextFrame(Int32 timeoutInMilliseconds, OutputDuplicateFrameInformation& frameInfoRef, Resource& desktopResourceOut)
   at Duplicator.Duplicator.AcquireFrame() in D:\Users\Levi\Downloads\Duplicator-master\Duplicator-master\Duplicator\Duplicator\Duplicator.cs:line 480
   at Duplicator.Duplicator.SafeAcquireFrame() in D:\Users\Levi\Downloads\Duplicator-master\Duplicator-master\Duplicator\Duplicator\Duplicator.cs:line 437
   at Duplicator.Duplicator.DuplicationThreadFunc() in D:\Users\Levi\Downloads\Duplicator-master\Duplicator-master\Duplicator\Duplicator\Duplicator.cs:line 618
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by smourier** [comment]
Hi,

Yes it's a know limitation of it. I have no time to invest in it right now. I will delete this repository anyway :-)
